package com.isaacpc.mariskalrock.bd;

import java.text.SimpleDateFormat;
import java.util.Locale;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

// KEEP INCLUDES END
/**
 * Entity mapped to table PODCAST_ENTITY.
 */
public class PodcastEntity {

    private Long id;
    /** Not-null value. */
    private String title;
    private String author;
    /** Not-null value. */
    private String link;
    private String imageURL;
    private String description;
    /** Not-null value. */
    private java.util.Date date;
    private boolean favorite;

    // KEEP FIELDS - put your custom fields here
    static SimpleDateFormat FORMATTER = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.ENGLISH);
    static SimpleDateFormat FORMATO_PANTALLA = new SimpleDateFormat("dd/MM/yy HH:mm", Locale.ENGLISH);

    // KEEP FIELDS END

    public PodcastEntity() {
    }

    public PodcastEntity(Long id) {
	this.id = id;
    }

    public PodcastEntity(Long id, String title, String author, String link, String imageURL, String description, java.util.Date date, boolean favorite) {
	this.id = id;
	this.title = title;
	this.author = author;
	this.link = link;
	this.imageURL = imageURL;
	this.description = description;
	this.date = date;
	this.favorite = favorite;
    }

    public Long getId() {
	return id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
	return title;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setTitle(String title) {
	this.title = title;
    }

    public String getAuthor() {
	return author;
    }

    public void setAuthor(String author) {
	this.author = author;
    }

    /** Not-null value. */
    public String getLink() {
	return link;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setLink(String link) {
	this.link = link;
    }

    public String getImageURL() {
	return imageURL;
    }

    public void setImageURL(String imageURL) {
	this.imageURL = imageURL;
    }

    public String getDescription() {
	return description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
	return date;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setDate(java.util.Date date) {
	this.date = date;
    }

    public boolean getFavorite() {
	return favorite;
    }

    public void setFavorite(boolean favorite) {
	this.favorite = favorite;
    }

    // KEEP METHODS - put your custom methods here
    public void setDateString(String date) {
	try {
	    this.date = FORMATTER.parse(date);
	} catch (java.text.ParseException e) {
	    e.printStackTrace();
	}
    }

    public String getDateString() {

	String fecha = FORMATO_PANTALLA.format(date);
	return fecha;
    }

    // KEEP METHODS END

}
