package com.isaacpc.mariskalrock.bd;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table VIDEO_ENTITY.
 */
public class VideoEntityDao extends AbstractDao<VideoEntity, Long> {

    public static final String TABLENAME = "VIDEO_ENTITY";

    /**
     * Properties of entity VideoEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
	public final static Property Id = new Property(0, Long.class, "id", true, "_id");
	public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
	public final static Property Logo = new Property(2, String.class, "logo", false, "LOGO");
	public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
	public final static Property ImageURL = new Property(4, String.class, "imageURL", false, "IMAGE_URL");
	public final static Property Duration = new Property(5, String.class, "duration", false, "DURATION");
	public final static Property ViewCount = new Property(6, String.class, "viewCount", false, "VIEW_COUNT");
	public final static Property Rating = new Property(7, float.class, "rating", false, "RATING");
	public final static Property Uploaded = new Property(8, String.class, "uploaded", false, "UPLOADED");
	public final static Property Url = new Property(9, String.class, "url", false, "URL");
	public final static Property Published = new Property(10, java.util.Date.class, "published", false, "PUBLISHED");
	public final static Property Favorite = new Property(11, boolean.class, "favorite", false, "FAVORITE");
    };

    public VideoEntityDao(DaoConfig config) {
	super(config);
    }

    public VideoEntityDao(DaoConfig config, DaoSession daoSession) {
	super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
	final String constraint = ifNotExists ? "IF NOT EXISTS " : "";
	db.execSQL("CREATE TABLE " + constraint + "'VIDEO_ENTITY' (" + //
		"'_id' INTEGER PRIMARY KEY ," + // 0: id
		"'TITLE' TEXT NOT NULL ," + // 1: title
		"'LOGO' TEXT," + // 2: logo
		"'DESCRIPTION' TEXT," + // 3: description
		"'IMAGE_URL' TEXT," + // 4: imageURL
		"'DURATION' TEXT NOT NULL ," + // 5: duration
		"'VIEW_COUNT' TEXT NOT NULL ," + // 6: viewCount
		"'RATING' REAL NOT NULL ," + // 7: rating
		"'UPLOADED' TEXT NOT NULL ," + // 8: uploaded
		"'URL' TEXT NOT NULL ," + // 9: url
		"'PUBLISHED' INTEGER NOT NULL ," + // 10: published
		"'FAVORITE' INTEGER NOT NULL );"); // 11: favorite
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
	final String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VIDEO_ENTITY'";
	db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VideoEntity entity) {
	stmt.clearBindings();

	final Long id = entity.getId();
	if (id != null) {
	    stmt.bindLong(1, id);
	}
	stmt.bindString(2, entity.getTitle());

	final String logo = entity.getLogo();
	if (logo != null) {
	    stmt.bindString(3, logo);
	}

	final String description = entity.getDescription();
	if (description != null) {
	    stmt.bindString(4, description);
	}

	final String imageURL = entity.getImageURL();
	if (imageURL != null) {
	    stmt.bindString(5, imageURL);
	}
	stmt.bindString(6, entity.getDuration());
	stmt.bindString(7, entity.getViewCount());
	stmt.bindDouble(8, entity.getRating());
	stmt.bindString(9, entity.getUploaded());
	stmt.bindString(10, entity.getUrl());
	stmt.bindLong(11, entity.getPublished().getTime());
	stmt.bindLong(12, entity.getFavorite() ? 1l : 0l);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
	return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public VideoEntity readEntity(Cursor cursor, int offset) {
	final VideoEntity entity = new VideoEntity(
		cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
			cursor.getString(offset + 1), // title
			cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // logo
				cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
					cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // imageURL
						cursor.getString(offset + 5), // duration
						cursor.getString(offset + 6), // viewCount
						cursor.getFloat(offset + 7), // rating
						cursor.getString(offset + 8), // uploaded
						cursor.getString(offset + 9), // url
						new java.util.Date(cursor.getLong(offset + 10)), // published
						cursor.getShort(offset + 11) != 0 // favorite
		);
	return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VideoEntity entity, int offset) {
	entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
	entity.setTitle(cursor.getString(offset + 1));
	entity.setLogo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
	entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
	entity.setImageURL(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
	entity.setDuration(cursor.getString(offset + 5));
	entity.setViewCount(cursor.getString(offset + 6));
	entity.setRating(cursor.getFloat(offset + 7));
	entity.setUploaded(cursor.getString(offset + 8));
	entity.setUrl(cursor.getString(offset + 9));
	entity.setPublished(new java.util.Date(cursor.getLong(offset + 10)));
	entity.setFavorite(cursor.getShort(offset + 11) != 0);
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(VideoEntity entity, long rowId) {
	entity.setId(rowId);
	return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(VideoEntity entity) {
	if (entity != null) {
	    return entity.getId();
	} else {
	    return null;
	}
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
	return true;
    }

}
