package com.isaacpc.mariskalrock.bd;

import java.text.SimpleDateFormat;
import java.util.Locale;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table VIDEO_ENTITY.
 */
public class VideoEntity {

    private Long id;
    /** Not-null value. */
    private String title;
    private String logo;
    private String description;
    private String imageURL;
    /** Not-null value. */
    private String duration;
    /** Not-null value. */
    private String viewCount;
    private float rating;
    /** Not-null value. */
    private String uploaded;
    /** Not-null value. */
    private String url;
    /** Not-null value. */
    private java.util.Date published;
    private boolean favorite;

    // KEEP FIELDS - put your custom fields here

    static SimpleDateFormat FORMATTER = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.ENGLISH);
    static SimpleDateFormat FORMATO_PANTALLA = new SimpleDateFormat("dd/MM/yy HH:mm", Locale.ENGLISH);

    // KEEP FIELDS END

    public VideoEntity() {
    }

    public VideoEntity(Long id) {
	this.id = id;
    }

    public VideoEntity(Long id, String title, String logo, String description, String imageURL, String duration, String viewCount, float rating,
	    String uploaded, String url, java.util.Date published, boolean favorite) {
	this.id = id;
	this.title = title;
	this.logo = logo;
	this.description = description;
	this.imageURL = imageURL;
	this.duration = duration;
	this.viewCount = viewCount;
	this.rating = rating;
	this.uploaded = uploaded;
	this.url = url;
	this.published = published;
	this.favorite = favorite;
    }

    public Long getId() {
	return id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
	return title;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setTitle(String title) {
	this.title = title;
    }

    public String getLogo() {
	return logo;
    }

    public void setLogo(String logo) {
	this.logo = logo;
    }

    public String getDescription() {
	return description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    public String getImageURL() {
	return imageURL;
    }

    public void setImageURL(String imageURL) {
	this.imageURL = imageURL;
    }

    /** Not-null value. */
    public String getDuration() {
	return duration;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setDuration(String duration) {
	this.duration = duration;
    }

    /** Not-null value. */
    public String getViewCount() {
	return viewCount;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setViewCount(String viewCount) {
	this.viewCount = viewCount;
    }

    public float getRating() {
	return rating;
    }

    public void setRating(float rating) {
	this.rating = rating;
    }

    /** Not-null value. */
    public String getUploaded() {
	return uploaded;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setUploaded(String uploaded) {
	this.uploaded = uploaded;
    }

    /** Not-null value. */
    public String getUrl() {
	return url;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setUrl(String url) {
	this.url = url;
    }

    /** Not-null value. */
    public java.util.Date getPublished() {

	return published;
    }

    /** Not-null value. */
    public String getPublishedString() {

	String fecha = FORMATO_PANTALLA.format(published);
	return fecha;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setPublished(java.util.Date published) {
	this.published = published;
    }

    public boolean getFavorite() {
	return favorite;
    }

    public void setFavorite(boolean favorite) {
	this.favorite = favorite;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
